# Generated by Django 5.0.6 on 2024-08-23 21:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_community2_delete_community'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Community2',
            new_name='Community',
        ),
    ]
