# Generated by Django 5.0.6 on 2024-08-26 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0012_communityimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityEventRegistration2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('student_number', models.CharField(max_length=50)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_member', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.communityevent')),
            ],
        ),
        migrations.DeleteModel(
            name='CommunityEventRegistration',
        ),
    ]
