# Generated by Django 5.0.6 on 2024-08-26 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0013_communityeventregistration2_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommunityEventRegistration2',
            new_name='CommunityEventRegistration',
        ),
    ]
