# Generated by Django 5.0.6 on 2024-09-02 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0014_rename_communityeventregistration2_communityeventregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=15)),
                ('student_number', models.CharField(max_length=20)),
                ('is_member', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.event')),
            ],
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
