# Generated by Django 5.0.6 on 2024-09-02 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0015_registration2_delete_registration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration2',
            new_name='Registration',
        ),
    ]
