# Generated by Django 5.0.6 on 2024-10-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0016_rename_registration2_registration"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="certificate",
            field=models.ImageField(blank=True, null=True, upload_to="certificates/"),
        ),
    ]
