# Generated by Django 5.0.6 on 2024-10-28 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0017_announcement_certificate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="announcement",
            name="certificate",
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("certificate_file", models.ImageField(upload_to="certificates/")),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="mainpage.announcement",
                    ),
                ),
            ],
        ),
    ]
