# Generated by Django 5.0.6 on 2024-10-28 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0018_remove_announcement_certificate_certificate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="certificate",
            old_name="certificate_file",
            new_name="certificate_image",
        ),
    ]
